# Generated by Django 4.0.3 on 2022-07-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='active',
        ),
        migrations.AddField(
            model_name='categorie',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2),
        ),
    ]
